name: Angular Build
on:
  push:
    branches: [ main, master ] # Triggers on pushes to main or master branch
  pull_request:
    branches: [ main, master ] # Triggers on pull requests to main or master branch

jobs:
  build:
    name: Build ${{ matrix.os }} with Node ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: ['20.19.x','22.12.x']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Enables caching for npm dependencies

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Application
        run: npm run build

      - name: Lint Code
        run: npm run lint

      - name: Lint css & scss
        run: npm run lint:css

      # - name: Run Tests
      #   run: npm run test

      #Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-app-dist-${{ matrix.os }}-${{ matrix.node-version }}
          path: docs/
          if-no-files-found: error